name: Build and Deploy to AKS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.10.3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/flask-app:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/flask-app:latest

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

#    - name: Terraform Init
#      working-directory: ./terraform
#      run: terraform init

#    - name: Terraform Plan
#      working-directory: ./terraform
#      run: terraform plan

#    - name: Terraform Apply
#      working-directory: ./terraform
#      run: terraform apply -auto-approve || true

    - name: Set AKS context
      uses: azure/aks-set-context@v3
      with:
        resource-group: ${{ secrets.AKS_RESOURCE_GROUP }}
        cluster-name: ${{ secrets.AKS_CLUSTER_NAME }}

    - name: Deploy to AKS
      uses: azure/k8s-deploy@v1
      with:
        manifests: |
            ./k8s/deployment.yaml
            ./k8s/namespace.yaml
 #           ./k8s/service.yaml
        images: |
            ${{ secrets.DOCKER_USERNAME }}/flask-app:latest

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.12.3

    - name: Deploy Prometheus
      run: |
        helm install prometheus prometheus-community/prometheus --namespace monitoring

    - name: Deploy Grafana
      run: |
        helm install grafana grafana/grafana --namespace monitoring